#!/bin/mksh
CNAME="BGPmon"
COU="netsec"
CO="CSU"
CCITY="ft. collins"
CSTATE="Colorado"
CCOUNTRY="US"
set -A hosts foo
typeset -N10 iter
iter=0
PASS=$1
shift
for HOSTNAME in "$@"; do
	echo "generating keystore and pubkeypair for" $HOSTNAME "with pass:" $PASS
	printf '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n\n' "$PASS" "$PASS" "$CNAME" "$COU" "$CO" "$CCITY" "$CSTATE" "$CCOUNTRY" "yes" | 
	keytool -genkey -keyalg RSA -alias $HOSTNAME -keystore .keystore-$HOSTNAME
	printf '%s\n' "$PASS" |
	keytool -export -alias $HOSTNAME -file cassandra-$HOSTNAME.cer -keystore .keystore-$HOSTNAME
	hosts[$iter]=$HOSTNAME
	((iter=iter+1))
done
iter=0
for host in ${hosts[@]}; do 
	if [[ $iter -eq 0 ]]; then
		printf '%s\n%s\n%s\n' "$PASS" "$PASS" "yes" |
		keytool -import -v -trustcacerts -alias $host -file cassandra-$host.cer -keystore .truststore
	else 
		printf '%s\n%s\n' "$PASS" "yes" |
		keytool -import -v -trustcacerts -alias $host -file cassandra-$host.cer -keystore .truststore
	fi
	((iter=iter+1))
done
