# Basic BGPmonD configuration
Address = ":12289"
DebugOut = "stdout"
ErrorOut = "stderr"

# Configuration for Modules
[Modules.GoBGPLink]

[Modules.Location]
    Keyspaces = ["csu_location_core"]

[Modules.PrefixByAsNumber]
    Keyspaces = ["csu_bgp_derived"]
    WriteKeyspace = "csu_bgp_derived"

[Modules.PrefixHijack]
    Keyspaces = ["csu_bgp_derived"]
    TimeBucketSize = 86400

# Configuration for Sessions
#[[Sessions.Cassandra.Writers.BGPUpdateMsgByTime]]
#    Keyspace = "csu_bgp_core"
#    TimeBucketSeconds = 86400

#[[Sessions.Cassandra.Writers.BGPUpdateMsgByPrefixRange]]
#    Keyspace = "csu_bgp_derived"
#    TimeBucketSeconds = 86400

[[Sessions.Cassandra.Writers.BGPCaptureByTime]]
    Keyspace = "csu_bgp_core"
    TimeBucketSeconds = 86400

[[Sessions.Cassandra.Writers.LocationByAS]]
    Keyspace = "csu_location_core"

[[Sessions.Cassandra.Writers.LocationByIPAddress]]
    Keyspace = "csu_location_core"

[[Sessions.Cassandra.Writers.LocationByPrefix]]
    Keyspace = "csu_location_core"

# Configuration for CockroachDB
[[Sessions.Cockroach.Writers.BGPCapture]]
    Table = "updates"
    Database = "bgpmon"
