# Basic BGPmonD configuration
Address = ":12289"
DebugOut = "discard"
ErrorOut = "stderr"

# Configuration for Prefix Hijack Modules
[Modules.PrefixHijack]
Keyspaces = ["csu_bgp_derived", "test_derived"]

# Conffiguration for GoBGP Link Modules
[Modules.GoBGPLink]

# Configuration for Cassandra Sessions
[[Sessions.Cassandra.MessageTypes.ASNumberLocation]]
Statement = "INSERT INTO csu_location_core.location_by_as_number(measure_date, as_number, country_code, state_code, city, latitude, longitude) VALUES(?,?,?,?,?,?,?)"
Values = ["MeasureDate", "ASNumber", "CountryCode", "StateCode", "City", "Latitude", "Longitude"]

#[[Sessions.Cassandra.MessageTypes.BGPUpdateMessage]]
#Statement = "INSERT INTO csu_bgp_core.update_messages_by_time() VALUES()"
#Values = ["PeerIPAddress", "CollectorIPAddress", "AnnouncedPrefixes", "ASPath"]

#[[Sessions.Cassandra.MessageTypes.BGPUpdateMessage]]
#Statement = "INSERT INTO csu_bgp_derived.as_number_by_prefix_range() VALUES()"

[[Sessions.Cassandra.MessageTypes.IPAddressLocation]]
Statement = "INSERT INTO csu_location_core.location_by_ip_address(measure_date, ip_address, country_code, state_code, city, latitude, longitude) VALUES(?,?,?,?,?,?,?)"
Values = ["MeasureDate", "IPAddress", "CountryCode", "StateCode", "City", "Latitude", "Longitude"]

[[Sessions.Cassandra.MessageTypes.PrefixLocation]]
Statement = "INSERT INTO csu_location_core.location_by_prefix(measure_date, prefix_ip_address, prefix_mask, country_code, state_code, city, latitude, longitude) VALUES(?,?,?,?,?,?,?)"
Values = ["MeasureDate", "PrefixIPAddress", "PrefixMask", "CountryCode", "StateCode", "City", "Latitude", "Longitude"]

# Configuration for File Sessions
[Sessions.File]
