// Code generated by protoc-gen-go.
// source: protobuf/bgpmond.proto
// DO NOT EDIT!

/*
Package bgpmond is a generated protocol buffer package.

It is generated from these files:
	protobuf/bgpmond.proto

It has these top-level messages:
	Empty
	GoBGPLinkModule
	PrefixHijackModule
	ListModulesReply
	RunModuleRequest
	RunModuleReply
	StartModuleRequest
	StartModuleReply
	StopModuleRequest
	CassandraSession
	FileSession
	CloseSessionRequest
	ListSessionsReply
	OpenSessionRequest
	OpenSessionReply
	WriteRequest
	ASNumberLocation
	BGPUpdateMessage
	IPAddressLocation
	IPPrefix
	Location
	PrefixLocation
*/
package bgpmond

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// Module Messages
type ModuleType int32

const (
	ModuleType_GOBGP_LINK    ModuleType = 0
	ModuleType_PREFIX_HIJACK ModuleType = 1
)

var ModuleType_name = map[int32]string{
	0: "GOBGP_LINK",
	1: "PREFIX_HIJACK",
}
var ModuleType_value = map[string]int32{
	"GOBGP_LINK":    0,
	"PREFIX_HIJACK": 1,
}

func (x ModuleType) String() string {
	return proto.EnumName(ModuleType_name, int32(x))
}
func (ModuleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

//
// Session Messages
type SessionType int32

const (
	SessionType_CASSANDRA SessionType = 0
	SessionType_FILE      SessionType = 1
)

var SessionType_name = map[int32]string{
	0: "CASSANDRA",
	1: "FILE",
}
var SessionType_value = map[string]int32{
	"CASSANDRA": 0,
	"FILE":      1,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}
func (SessionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WriteRequest_Type int32

const (
	WriteRequest_AS_NUMBER_LOCATION  WriteRequest_Type = 0
	WriteRequest_BGP_UPDATE          WriteRequest_Type = 1
	WriteRequest_IP_ADDRESS_LOCATION WriteRequest_Type = 2
	WriteRequest_PREFIX_LOCATION     WriteRequest_Type = 3
)

var WriteRequest_Type_name = map[int32]string{
	0: "AS_NUMBER_LOCATION",
	1: "BGP_UPDATE",
	2: "IP_ADDRESS_LOCATION",
	3: "PREFIX_LOCATION",
}
var WriteRequest_Type_value = map[string]int32{
	"AS_NUMBER_LOCATION":  0,
	"BGP_UPDATE":          1,
	"IP_ADDRESS_LOCATION": 2,
	"PREFIX_LOCATION":     3,
}

func (x WriteRequest_Type) String() string {
	return proto.EnumName(WriteRequest_Type_name, int32(x))
}
func (WriteRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GoBGPLinkModule struct {
	Address      string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	OutSessionId []string `protobuf:"bytes,2,rep,name=out_session_id,json=outSessionId" json:"out_session_id,omitempty"`
}

func (m *GoBGPLinkModule) Reset()                    { *m = GoBGPLinkModule{} }
func (m *GoBGPLinkModule) String() string            { return proto.CompactTextString(m) }
func (*GoBGPLinkModule) ProtoMessage()               {}
func (*GoBGPLinkModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PrefixHijackModule struct {
	Prefix          string   `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	AsNumber        []uint32 `protobuf:"varint,2,rep,name=as_number,json=asNumber" json:"as_number,omitempty"`
	PeriodicSeconds int32    `protobuf:"varint,3,opt,name=periodic_seconds,json=periodicSeconds" json:"periodic_seconds,omitempty"`
	TimeoutSeconds  int32    `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds" json:"timeout_seconds,omitempty"`
	InSessionId     []string `protobuf:"bytes,5,rep,name=in_session_id,json=inSessionId" json:"in_session_id,omitempty"`
}

func (m *PrefixHijackModule) Reset()                    { *m = PrefixHijackModule{} }
func (m *PrefixHijackModule) String() string            { return proto.CompactTextString(m) }
func (*PrefixHijackModule) ProtoMessage()               {}
func (*PrefixHijackModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

//
// Module Command Messages
type ListModulesReply struct {
	ModuleId []string `protobuf:"bytes,1,rep,name=module_id,json=moduleId" json:"module_id,omitempty"`
}

func (m *ListModulesReply) Reset()                    { *m = ListModulesReply{} }
func (m *ListModulesReply) String() string            { return proto.CompactTextString(m) }
func (*ListModulesReply) ProtoMessage()               {}
func (*ListModulesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RunModuleRequest struct {
	Type               ModuleType          `protobuf:"varint,1,opt,name=type,enum=bgpmond.ModuleType" json:"type,omitempty"`
	PrefixHijackModule *PrefixHijackModule `protobuf:"bytes,2,opt,name=prefix_hijack_module,json=prefixHijackModule" json:"prefix_hijack_module,omitempty"`
}

func (m *RunModuleRequest) Reset()                    { *m = RunModuleRequest{} }
func (m *RunModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*RunModuleRequest) ProtoMessage()               {}
func (*RunModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RunModuleRequest) GetPrefixHijackModule() *PrefixHijackModule {
	if m != nil {
		return m.PrefixHijackModule
	}
	return nil
}

type RunModuleReply struct {
	ModuleMessage string `protobuf:"bytes,3,opt,name=module_message,json=moduleMessage" json:"module_message,omitempty"`
}

func (m *RunModuleReply) Reset()                    { *m = RunModuleReply{} }
func (m *RunModuleReply) String() string            { return proto.CompactTextString(m) }
func (*RunModuleReply) ProtoMessage()               {}
func (*RunModuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StartModuleRequest struct {
	Type               ModuleType          `protobuf:"varint,1,opt,name=type,enum=bgpmond.ModuleType" json:"type,omitempty"`
	ModuleId           string              `protobuf:"bytes,2,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
	GobgpLinkModule    *GoBGPLinkModule    `protobuf:"bytes,3,opt,name=gobgp_link_module,json=gobgpLinkModule" json:"gobgp_link_module,omitempty"`
	PrefixHijackModule *PrefixHijackModule `protobuf:"bytes,4,opt,name=prefix_hijack_module,json=prefixHijackModule" json:"prefix_hijack_module,omitempty"`
}

func (m *StartModuleRequest) Reset()                    { *m = StartModuleRequest{} }
func (m *StartModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*StartModuleRequest) ProtoMessage()               {}
func (*StartModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartModuleRequest) GetGobgpLinkModule() *GoBGPLinkModule {
	if m != nil {
		return m.GobgpLinkModule
	}
	return nil
}

func (m *StartModuleRequest) GetPrefixHijackModule() *PrefixHijackModule {
	if m != nil {
		return m.PrefixHijackModule
	}
	return nil
}

type StartModuleReply struct {
	ModuleId string `protobuf:"bytes,3,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
}

func (m *StartModuleReply) Reset()                    { *m = StartModuleReply{} }
func (m *StartModuleReply) String() string            { return proto.CompactTextString(m) }
func (*StartModuleReply) ProtoMessage()               {}
func (*StartModuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StopModuleRequest struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
}

func (m *StopModuleRequest) Reset()                    { *m = StopModuleRequest{} }
func (m *StopModuleRequest) String() string            { return proto.CompactTextString(m) }
func (*StopModuleRequest) ProtoMessage()               {}
func (*StopModuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CassandraSession struct {
	Username    string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password    string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Hosts       []string `protobuf:"bytes,3,rep,name=hosts" json:"hosts,omitempty"`
	WorkerCount uint32   `protobuf:"varint,4,opt,name=workerCount" json:"workerCount,omitempty"`
}

func (m *CassandraSession) Reset()                    { *m = CassandraSession{} }
func (m *CassandraSession) String() string            { return proto.CompactTextString(m) }
func (*CassandraSession) ProtoMessage()               {}
func (*CassandraSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type FileSession struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
}

func (m *FileSession) Reset()                    { *m = FileSession{} }
func (m *FileSession) String() string            { return proto.CompactTextString(m) }
func (*FileSession) ProtoMessage()               {}
func (*FileSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

//
// Session Command Messages
type CloseSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *CloseSessionRequest) Reset()                    { *m = CloseSessionRequest{} }
func (m *CloseSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionRequest) ProtoMessage()               {}
func (*CloseSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ListSessionsReply struct {
	SessionId []string `protobuf:"bytes,1,rep,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *ListSessionsReply) Reset()                    { *m = ListSessionsReply{} }
func (m *ListSessionsReply) String() string            { return proto.CompactTextString(m) }
func (*ListSessionsReply) ProtoMessage()               {}
func (*ListSessionsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type OpenSessionRequest struct {
	Type             SessionType       `protobuf:"varint,1,opt,name=type,enum=bgpmond.SessionType" json:"type,omitempty"`
	SessionId        string            `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	CassandraSession *CassandraSession `protobuf:"bytes,3,opt,name=cassandra_session,json=cassandraSession" json:"cassandra_session,omitempty"`
	FileSession      *FileSession      `protobuf:"bytes,4,opt,name=file_session,json=fileSession" json:"file_session,omitempty"`
}

func (m *OpenSessionRequest) Reset()                    { *m = OpenSessionRequest{} }
func (m *OpenSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionRequest) ProtoMessage()               {}
func (*OpenSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OpenSessionRequest) GetCassandraSession() *CassandraSession {
	if m != nil {
		return m.CassandraSession
	}
	return nil
}

func (m *OpenSessionRequest) GetFileSession() *FileSession {
	if m != nil {
		return m.FileSession
	}
	return nil
}

type OpenSessionReply struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *OpenSessionReply) Reset()                    { *m = OpenSessionReply{} }
func (m *OpenSessionReply) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionReply) ProtoMessage()               {}
func (*OpenSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

//
// Write Messages
type WriteRequest struct {
	Type              WriteRequest_Type  `protobuf:"varint,1,opt,name=type,enum=bgpmond.WriteRequest_Type" json:"type,omitempty"`
	SessionId         string             `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AsNumberLocation  *ASNumberLocation  `protobuf:"bytes,3,opt,name=as_number_location,json=asNumberLocation" json:"as_number_location,omitempty"`
	BgpUpdateMessage  *BGPUpdateMessage  `protobuf:"bytes,4,opt,name=bgp_update_message,json=bgpUpdateMessage" json:"bgp_update_message,omitempty"`
	IpAddressLocation *IPAddressLocation `protobuf:"bytes,5,opt,name=ip_address_location,json=ipAddressLocation" json:"ip_address_location,omitempty"`
	PrefixLocation    *PrefixLocation    `protobuf:"bytes,6,opt,name=prefix_location,json=prefixLocation" json:"prefix_location,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *WriteRequest) GetAsNumberLocation() *ASNumberLocation {
	if m != nil {
		return m.AsNumberLocation
	}
	return nil
}

func (m *WriteRequest) GetBgpUpdateMessage() *BGPUpdateMessage {
	if m != nil {
		return m.BgpUpdateMessage
	}
	return nil
}

func (m *WriteRequest) GetIpAddressLocation() *IPAddressLocation {
	if m != nil {
		return m.IpAddressLocation
	}
	return nil
}

func (m *WriteRequest) GetPrefixLocation() *PrefixLocation {
	if m != nil {
		return m.PrefixLocation
	}
	return nil
}

type ASNumberLocation struct {
	AsNumber    uint32    `protobuf:"varint,1,opt,name=as_number,json=asNumber" json:"as_number,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date,json=measureDate" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Source      string    `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *ASNumberLocation) Reset()                    { *m = ASNumberLocation{} }
func (m *ASNumberLocation) String() string            { return proto.CompactTextString(m) }
func (*ASNumberLocation) ProtoMessage()               {}
func (*ASNumberLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ASNumberLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type BGPUpdateMessage struct {
	Timestamp          int64       `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	CollectorIpAddress string      `protobuf:"bytes,2,opt,name=collector_ip_address,json=collectorIpAddress" json:"collector_ip_address,omitempty"`
	CollectorMac       string      `protobuf:"bytes,3,opt,name=collector_mac,json=collectorMac" json:"collector_mac,omitempty"`
	CollectorPort      uint32      `protobuf:"varint,4,opt,name=collector_port,json=collectorPort" json:"collector_port,omitempty"`
	PeerIpAddress      string      `protobuf:"bytes,5,opt,name=peer_ip_address,json=peerIpAddress" json:"peer_ip_address,omitempty"`
	AsPath             []uint32    `protobuf:"varint,6,rep,name=as_path,json=asPath" json:"as_path,omitempty"`
	NextHop            string      `protobuf:"bytes,9,opt,name=next_hop,json=nextHop" json:"next_hop,omitempty"`
	AdvertisedRoutes   []*IPPrefix `protobuf:"bytes,7,rep,name=advertised_routes,json=advertisedRoutes" json:"advertised_routes,omitempty"`
	WithdrawnRoutes    []*IPPrefix `protobuf:"bytes,8,rep,name=withdrawn_routes,json=withdrawnRoutes" json:"withdrawn_routes,omitempty"`
}

func (m *BGPUpdateMessage) Reset()                    { *m = BGPUpdateMessage{} }
func (m *BGPUpdateMessage) String() string            { return proto.CompactTextString(m) }
func (*BGPUpdateMessage) ProtoMessage()               {}
func (*BGPUpdateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *BGPUpdateMessage) GetAdvertisedRoutes() []*IPPrefix {
	if m != nil {
		return m.AdvertisedRoutes
	}
	return nil
}

func (m *BGPUpdateMessage) GetWithdrawnRoutes() []*IPPrefix {
	if m != nil {
		return m.WithdrawnRoutes
	}
	return nil
}

type IPAddressLocation struct {
	IpAddress   string    `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress" json:"ip_address,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date,json=measureDate" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Source      string    `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *IPAddressLocation) Reset()                    { *m = IPAddressLocation{} }
func (m *IPAddressLocation) String() string            { return proto.CompactTextString(m) }
func (*IPAddressLocation) ProtoMessage()               {}
func (*IPAddressLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *IPAddressLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type IPPrefix struct {
	PrefixIpAddress string `protobuf:"bytes,1,opt,name=prefix_ip_address,json=prefixIpAddress" json:"prefix_ip_address,omitempty"`
	PrefixMask      uint32 `protobuf:"varint,2,opt,name=prefix_mask,json=prefixMask" json:"prefix_mask,omitempty"`
}

func (m *IPPrefix) Reset()                    { *m = IPPrefix{} }
func (m *IPPrefix) String() string            { return proto.CompactTextString(m) }
func (*IPPrefix) ProtoMessage()               {}
func (*IPPrefix) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type Location struct {
	CountryCode string  `protobuf:"bytes,1,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	StateCode   string  `protobuf:"bytes,2,opt,name=state_code,json=stateCode" json:"state_code,omitempty"`
	City        string  `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Latitude    float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type PrefixLocation struct {
	Prefix      *IPPrefix `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date,json=measureDate" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Source      string    `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *PrefixLocation) Reset()                    { *m = PrefixLocation{} }
func (m *PrefixLocation) String() string            { return proto.CompactTextString(m) }
func (*PrefixLocation) ProtoMessage()               {}
func (*PrefixLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PrefixLocation) GetPrefix() *IPPrefix {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *PrefixLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "bgpmond.Empty")
	proto.RegisterType((*GoBGPLinkModule)(nil), "bgpmond.GoBGPLinkModule")
	proto.RegisterType((*PrefixHijackModule)(nil), "bgpmond.PrefixHijackModule")
	proto.RegisterType((*ListModulesReply)(nil), "bgpmond.ListModulesReply")
	proto.RegisterType((*RunModuleRequest)(nil), "bgpmond.RunModuleRequest")
	proto.RegisterType((*RunModuleReply)(nil), "bgpmond.RunModuleReply")
	proto.RegisterType((*StartModuleRequest)(nil), "bgpmond.StartModuleRequest")
	proto.RegisterType((*StartModuleReply)(nil), "bgpmond.StartModuleReply")
	proto.RegisterType((*StopModuleRequest)(nil), "bgpmond.StopModuleRequest")
	proto.RegisterType((*CassandraSession)(nil), "bgpmond.CassandraSession")
	proto.RegisterType((*FileSession)(nil), "bgpmond.FileSession")
	proto.RegisterType((*CloseSessionRequest)(nil), "bgpmond.CloseSessionRequest")
	proto.RegisterType((*ListSessionsReply)(nil), "bgpmond.ListSessionsReply")
	proto.RegisterType((*OpenSessionRequest)(nil), "bgpmond.OpenSessionRequest")
	proto.RegisterType((*OpenSessionReply)(nil), "bgpmond.OpenSessionReply")
	proto.RegisterType((*WriteRequest)(nil), "bgpmond.WriteRequest")
	proto.RegisterType((*ASNumberLocation)(nil), "bgpmond.ASNumberLocation")
	proto.RegisterType((*BGPUpdateMessage)(nil), "bgpmond.BGPUpdateMessage")
	proto.RegisterType((*IPAddressLocation)(nil), "bgpmond.IPAddressLocation")
	proto.RegisterType((*IPPrefix)(nil), "bgpmond.IPPrefix")
	proto.RegisterType((*Location)(nil), "bgpmond.Location")
	proto.RegisterType((*PrefixLocation)(nil), "bgpmond.PrefixLocation")
	proto.RegisterEnum("bgpmond.ModuleType", ModuleType_name, ModuleType_value)
	proto.RegisterEnum("bgpmond.SessionType", SessionType_name, SessionType_value)
	proto.RegisterEnum("bgpmond.WriteRequest_Type", WriteRequest_Type_name, WriteRequest_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Bgpmond service

type BgpmondClient interface {
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	ListModules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListModulesReply, error)
	ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsReply, error)
	RunModule(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleReply, error)
	StartModule(ctx context.Context, in *StartModuleRequest, opts ...grpc.CallOption) (*StartModuleReply, error)
	StopModule(ctx context.Context, in *StopModuleRequest, opts ...grpc.CallOption) (*Empty, error)
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionReply, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (Bgpmond_WriteClient, error)
}

type bgpmondClient struct {
	cc *grpc.ClientConn
}

func NewBgpmondClient(cc *grpc.ClientConn) BgpmondClient {
	return &bgpmondClient{cc}
}

func (c *bgpmondClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/CloseSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) ListModules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListModulesReply, error) {
	out := new(ListModulesReply)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/ListModules", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsReply, error) {
	out := new(ListSessionsReply)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/ListSessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) RunModule(ctx context.Context, in *RunModuleRequest, opts ...grpc.CallOption) (*RunModuleReply, error) {
	out := new(RunModuleReply)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/RunModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) StartModule(ctx context.Context, in *StartModuleRequest, opts ...grpc.CallOption) (*StartModuleReply, error) {
	out := new(StartModuleReply)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/StartModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) StopModule(ctx context.Context, in *StopModuleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/StopModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (*OpenSessionReply, error) {
	out := new(OpenSessionReply)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/OpenSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) Write(ctx context.Context, opts ...grpc.CallOption) (Bgpmond_WriteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Bgpmond_serviceDesc.Streams[0], c.cc, "/bgpmond.Bgpmond/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &bgpmondWriteClient{stream}
	return x, nil
}

type Bgpmond_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type bgpmondWriteClient struct {
	grpc.ClientStream
}

func (x *bgpmondWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bgpmondWriteClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Bgpmond service

type BgpmondServer interface {
	CloseSession(context.Context, *CloseSessionRequest) (*Empty, error)
	ListModules(context.Context, *Empty) (*ListModulesReply, error)
	ListSessions(context.Context, *Empty) (*ListSessionsReply, error)
	RunModule(context.Context, *RunModuleRequest) (*RunModuleReply, error)
	StartModule(context.Context, *StartModuleRequest) (*StartModuleReply, error)
	StopModule(context.Context, *StopModuleRequest) (*Empty, error)
	OpenSession(context.Context, *OpenSessionRequest) (*OpenSessionReply, error)
	Write(Bgpmond_WriteServer) error
}

func RegisterBgpmondServer(s *grpc.Server, srv BgpmondServer) {
	s.RegisterService(&_Bgpmond_serviceDesc, srv)
}

func _Bgpmond_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/CloseSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/ListModules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).ListModules(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/ListSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).ListSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_RunModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).RunModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/RunModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).RunModule(ctx, req.(*RunModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_StartModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).StartModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/StartModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).StartModule(ctx, req.(*StartModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_StopModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).StopModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/StopModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).StopModule(ctx, req.(*StopModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpmondServer).OpenSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bgpmond.Bgpmond/OpenSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpmondServer).OpenSession(ctx, req.(*OpenSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bgpmond_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BgpmondServer).Write(&bgpmondWriteServer{stream})
}

type Bgpmond_WriteServer interface {
	SendAndClose(*Empty) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type bgpmondWriteServer struct {
	grpc.ServerStream
}

func (x *bgpmondWriteServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bgpmondWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Bgpmond_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bgpmond.Bgpmond",
	HandlerType: (*BgpmondServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseSession",
			Handler:    _Bgpmond_CloseSession_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _Bgpmond_ListModules_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Bgpmond_ListSessions_Handler,
		},
		{
			MethodName: "RunModule",
			Handler:    _Bgpmond_RunModule_Handler,
		},
		{
			MethodName: "StartModule",
			Handler:    _Bgpmond_StartModule_Handler,
		},
		{
			MethodName: "StopModule",
			Handler:    _Bgpmond_StopModule_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _Bgpmond_OpenSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _Bgpmond_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protobuf/bgpmond.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x57, 0xdb, 0x6e, 0x1b, 0xe5,
	0x13, 0xef, 0xc6, 0x76, 0x62, 0x8f, 0xcf, 0x5f, 0xf2, 0x6f, 0x5c, 0xb7, 0x7f, 0x51, 0x16, 0x28,
	0x69, 0x25, 0xd2, 0x12, 0x90, 0x2a, 0xa1, 0x0a, 0xe1, 0x3a, 0x87, 0xba, 0xcd, 0xc1, 0xac, 0x5b,
	0x95, 0x0b, 0xa4, 0xd5, 0x66, 0xf7, 0x4b, 0xb2, 0xd4, 0xde, 0x5d, 0x76, 0xd7, 0xa4, 0xb9, 0xe5,
	0xaa, 0xe2, 0x0d, 0x40, 0xdc, 0xf2, 0x20, 0x3c, 0x07, 0x12, 0xaf, 0xc0, 0x2b, 0x30, 0xdf, 0x61,
	0xbf, 0x3d, 0xd8, 0x95, 0x50, 0x2f, 0x7a, 0xe7, 0x99, 0x9d, 0x99, 0x6f, 0xe6, 0x37, 0x47, 0xc3,
	0xf5, 0x20, 0xf4, 0x63, 0xff, 0x74, 0x7e, 0x76, 0xff, 0xf4, 0x3c, 0x98, 0xf9, 0x9e, 0xb3, 0xcd,
	0x19, 0x64, 0x4d, 0x92, 0xfa, 0x1a, 0x54, 0xf6, 0x66, 0x41, 0x7c, 0xa5, 0x7f, 0x0b, 0xed, 0x03,
	0xff, 0xf1, 0xc1, 0xf8, 0xd0, 0xf5, 0x5e, 0x1d, 0xf9, 0xce, 0x7c, 0x4a, 0x49, 0x0f, 0xd6, 0x2c,
	0xc7, 0x09, 0x69, 0x14, 0xf5, 0xb4, 0xdb, 0xda, 0x56, 0xcd, 0x48, 0x48, 0xf2, 0x31, 0xb4, 0xfc,
	0x79, 0x6c, 0x46, 0xf8, 0xdb, 0xf5, 0x3d, 0xd3, 0x75, 0x7a, 0x2b, 0xb7, 0x4b, 0x28, 0xd0, 0x40,
	0xee, 0x44, 0x30, 0x47, 0x8e, 0xfe, 0xa7, 0x06, 0x64, 0x1c, 0xd2, 0x33, 0xf7, 0xf5, 0x13, 0xf7,
	0x07, 0xcb, 0x4e, 0xcc, 0x5e, 0x87, 0xd5, 0x80, 0x73, 0xa5, 0x55, 0x49, 0x91, 0x9b, 0x50, 0xb3,
	0x22, 0xd3, 0x9b, 0xcf, 0x4e, 0x69, 0xc8, 0xed, 0x35, 0x8d, 0xaa, 0x15, 0x1d, 0x73, 0x9a, 0xdc,
	0x85, 0x4e, 0x40, 0x43, 0xd7, 0x77, 0x5c, 0x1b, 0x9f, 0xb5, 0xd1, 0xf5, 0xa8, 0x57, 0x42, 0xf5,
	0x8a, 0xd1, 0x4e, 0xf8, 0x13, 0xc1, 0x26, 0x9f, 0x42, 0x3b, 0x76, 0x67, 0x54, 0x38, 0x28, 0x24,
	0xcb, 0x5c, 0xb2, 0x25, 0xd9, 0x89, 0xa0, 0x0e, 0x4d, 0xd7, 0xcb, 0x06, 0x51, 0xe1, 0x41, 0xd4,
	0x5d, 0x2f, 0x8d, 0xe1, 0x3e, 0x74, 0x0e, 0xdd, 0x28, 0x16, 0xae, 0x47, 0x06, 0x0d, 0xa6, 0x57,
	0xcc, 0xd1, 0x19, 0xa7, 0x99, 0x8e, 0xc6, 0x75, 0xaa, 0x82, 0x81, 0x0a, 0xbf, 0x68, 0xd0, 0x31,
	0xe6, 0x9e, 0x50, 0x30, 0xe8, 0x8f, 0x73, 0x1a, 0xc5, 0xe8, 0x52, 0x39, 0xbe, 0x0a, 0x28, 0x0f,
	0xb8, 0xb5, 0xb3, 0xbe, 0x9d, 0x24, 0x43, 0x48, 0x3d, 0xc7, 0x4f, 0x06, 0x17, 0x20, 0x47, 0xb0,
	0x21, 0xd0, 0x30, 0x2f, 0x38, 0x64, 0xa6, 0xb0, 0x8b, 0x70, 0x68, 0x5b, 0xf5, 0x9d, 0x9b, 0x4a,
	0x71, 0x11, 0x56, 0x83, 0x04, 0x0b, 0x3c, 0xfd, 0x21, 0xb4, 0x32, 0xbe, 0x30, 0xdf, 0x3f, 0x81,
	0x96, 0xf4, 0x7d, 0x86, 0x31, 0x5a, 0xe7, 0x94, 0xa3, 0x58, 0x33, 0x9a, 0x82, 0x7b, 0x24, 0x98,
	0xfa, 0x3f, 0x98, 0xba, 0x49, 0x6c, 0x85, 0xf1, 0x3b, 0xc6, 0x91, 0x83, 0x68, 0x85, 0xbf, 0xa0,
	0x20, 0x22, 0xbb, 0xd0, 0x3d, 0xf7, 0x51, 0xd5, 0x9c, 0x62, 0xad, 0x25, 0x11, 0x96, 0x78, 0x84,
	0x3d, 0x65, 0xb2, 0x50, 0x8c, 0x46, 0x9b, 0xab, 0x64, 0xaa, 0xf3, 0x6d, 0x50, 0x95, 0xdf, 0x0d,
	0x2a, 0x4c, 0x74, 0x2e, 0xe0, 0x85, 0x44, 0x97, 0xf2, 0x51, 0xe8, 0x0f, 0xa0, 0x3b, 0x89, 0xfd,
	0x20, 0x0f, 0x50, 0xa1, 0x34, 0xf2, 0x1a, 0x3f, 0x63, 0x69, 0x0c, 0x2d, 0x04, 0xd8, 0x73, 0x42,
	0x4b, 0x96, 0x18, 0xe9, 0x43, 0x75, 0x1e, 0xd1, 0xd0, 0xb3, 0x66, 0x34, 0x51, 0x48, 0x68, 0xf6,
	0x2d, 0x40, 0xf9, 0x4b, 0x3f, 0x54, 0x20, 0x26, 0x34, 0xd9, 0x80, 0xca, 0x85, 0x1f, 0xc5, 0xac,
	0x0b, 0x58, 0x01, 0x0a, 0x82, 0xdc, 0x86, 0x3a, 0x7e, 0x7d, 0x45, 0xc3, 0xa1, 0x3f, 0xf7, 0x62,
	0x8e, 0x45, 0xd3, 0xc8, 0xb2, 0xf4, 0xbb, 0x50, 0xdf, 0x77, 0xa7, 0x34, 0xf3, 0xfc, 0x19, 0x92,
	0xd9, 0xe7, 0x13, 0x5a, 0xff, 0x12, 0xd6, 0x87, 0x53, 0x3f, 0x4a, 0x64, 0x93, 0x18, 0xff, 0x0f,
	0x90, 0xe9, 0x19, 0xa1, 0x54, 0x8b, 0x54, 0xc7, 0xec, 0x40, 0x97, 0x75, 0x8c, 0x54, 0x92, 0x2d,
	0x53, 0xd4, 0x29, 0xe5, 0x75, 0xfe, 0xc6, 0x72, 0x3b, 0x09, 0xa8, 0x57, 0x78, 0x69, 0x2b, 0x57,
	0x6e, 0x1b, 0x2a, 0xa5, 0x52, 0x2c, 0x53, 0x6f, 0x79, 0xfb, 0x2b, 0x05, 0x9f, 0xc8, 0x3e, 0x74,
	0xed, 0x04, 0xf8, 0xa4, 0xe1, 0x65, 0xc5, 0xdd, 0x50, 0x56, 0x8b, 0xa9, 0x31, 0x3a, 0x76, 0x31,
	0x59, 0x0f, 0xa1, 0xc1, 0xd0, 0x51, 0x26, 0x44, 0xad, 0xa5, 0x8e, 0x65, 0x90, 0x35, 0xea, 0x67,
	0x29, 0xa1, 0x7f, 0x0e, 0x9d, 0x5c, 0x7c, 0xcb, 0x30, 0x29, 0xe0, 0xf8, 0x57, 0x09, 0x1a, 0x2f,
	0x43, 0x37, 0x56, 0xb5, 0xb5, 0x9d, 0x43, 0xa3, 0xaf, 0x1e, 0xcd, 0x0a, 0x6d, 0xff, 0x77, 0x4c,
	0x0e, 0x80, 0xa8, 0x71, 0x6b, 0x4e, 0x7d, 0xdb, 0x8a, 0x97, 0x81, 0x32, 0x98, 0x88, 0x01, 0x7c,
	0x28, 0x05, 0x8c, 0x4e, 0x32, 0x92, 0x13, 0x0e, 0x33, 0xc4, 0x9a, 0x79, 0x1e, 0x38, 0x56, 0x9c,
	0x8e, 0x95, 0x72, 0xc1, 0x10, 0x76, 0xf3, 0x0b, 0x2e, 0x21, 0x47, 0x8c, 0xd1, 0xc1, 0x2f, 0x39,
	0x0e, 0x79, 0x0a, 0xeb, 0x6e, 0x60, 0xca, 0x1d, 0x93, 0xba, 0x54, 0xe1, 0x96, 0xd2, 0x78, 0x47,
	0xe3, 0x81, 0x10, 0x51, 0x3e, 0x75, 0xdd, 0xa0, 0xc0, 0x22, 0xdf, 0x40, 0x5b, 0x4e, 0x07, 0x65,
	0x67, 0x95, 0xdb, 0xd9, 0x2c, 0x0c, 0x06, 0x65, 0xa4, 0x15, 0xe4, 0x68, 0xfd, 0x7b, 0x28, 0x33,
	0x30, 0x71, 0x5d, 0x91, 0xc1, 0xc4, 0x3c, 0x7e, 0x71, 0xf4, 0x78, 0xcf, 0x30, 0x0f, 0x4f, 0x86,
	0x83, 0xe7, 0xa3, 0x93, 0xe3, 0xce, 0x35, 0xd2, 0x02, 0xc0, 0x98, 0xcc, 0x17, 0xe3, 0xdd, 0xc1,
	0xf3, 0xbd, 0x8e, 0x46, 0x36, 0x61, 0x7d, 0x34, 0x36, 0x07, 0xbb, 0xbb, 0xc6, 0xde, 0x64, 0x92,
	0x0a, 0xae, 0x90, 0x75, 0x68, 0x8f, 0x8d, 0xbd, 0xfd, 0xd1, 0x77, 0x29, 0xb3, 0xa4, 0xff, 0x8a,
	0xb3, 0xa0, 0x88, 0x6d, 0x7e, 0x03, 0x6a, 0xbc, 0x77, 0xd3, 0x0d, 0xf8, 0x21, 0x34, 0x66, 0xd4,
	0x8a, 0xe6, 0x21, 0x35, 0x19, 0x68, 0x32, 0xa1, 0x75, 0xc9, 0xdb, 0x45, 0x16, 0xf9, 0x0c, 0xaa,
	0x85, 0x44, 0x76, 0x55, 0xb4, 0x2a, 0x4e, 0x25, 0xc2, 0x16, 0x71, 0xe4, 0xcf, 0x43, 0x5b, 0x24,
	0x0b, 0x17, 0xb1, 0xa0, 0xf4, 0x37, 0x25, 0xe8, 0x14, 0xd3, 0x45, 0x6e, 0x41, 0x8d, 0xad, 0xcf,
	0x28, 0xb6, 0x66, 0x01, 0xf7, 0xad, 0x64, 0xa4, 0x0c, 0xf2, 0x00, 0x36, 0x6c, 0x7f, 0x3a, 0xa5,
	0x76, 0xec, 0x87, 0x66, 0x9a, 0x44, 0xe9, 0x24, 0x51, 0xdf, 0x46, 0x49, 0xa2, 0xc8, 0x47, 0xd0,
	0x4c, 0x35, 0x66, 0x96, 0x2d, 0xe7, 0x6b, 0x43, 0x31, 0x8f, 0x2c, 0x9b, 0x6d, 0xab, 0x54, 0x28,
	0xf0, 0xc3, 0x64, 0xa2, 0xa5, 0xaa, 0x63, 0x64, 0x92, 0x3b, 0x98, 0x6c, 0x4a, 0x73, 0x0f, 0x57,
	0xc4, 0x56, 0x63, 0xec, 0xf4, 0xcd, 0x4d, 0x3c, 0x68, 0x22, 0x33, 0xb0, 0xe2, 0x0b, 0x2c, 0x06,
	0x76, 0x5f, 0xac, 0x5a, 0xd1, 0x18, 0x29, 0x72, 0x03, 0xaa, 0x1e, 0x7d, 0x1d, 0x9b, 0x17, 0x7e,
	0xd0, 0xab, 0x89, 0x53, 0x87, 0xd1, 0x4f, 0xfc, 0x80, 0x7c, 0x0d, 0x5d, 0xcb, 0xf9, 0x89, 0x86,
	0xb1, 0x1b, 0x51, 0xc7, 0x0c, 0xf1, 0x7c, 0xa0, 0x51, 0x6f, 0x0d, 0xb5, 0xb3, 0xe0, 0x8e, 0xc6,
	0xa2, 0x98, 0xb0, 0x3b, 0x94, 0xac, 0xc1, 0x45, 0xc9, 0x23, 0xe8, 0x5c, 0xba, 0xf1, 0x05, 0x0e,
	0x91, 0x4b, 0x2f, 0x51, 0xaf, 0xbe, 0x4d, 0xbd, 0xad, 0x44, 0x85, 0xb6, 0xfe, 0xbb, 0x06, 0xdd,
	0x85, 0x7a, 0x67, 0x9d, 0x9d, 0x09, 0x55, 0x4e, 0x0e, 0xd5, 0x03, 0xef, 0xb1, 0x52, 0x5e, 0x42,
	0x35, 0xf1, 0x9d, 0xdc, 0x83, 0xae, 0xec, 0xb8, 0x05, 0xdf, 0x64, 0x2b, 0xa6, 0x89, 0xf8, 0x00,
	0xea, 0x52, 0x76, 0x66, 0x45, 0xaf, 0xb8, 0x83, 0x4d, 0x03, 0x04, 0xeb, 0x08, 0x39, 0xfa, 0x6f,
	0x1a, 0x54, 0x55, 0xb8, 0x18, 0x8f, 0xcd, 0x76, 0x57, 0x78, 0x65, 0xda, 0xbe, 0x93, 0xec, 0xa9,
	0xba, 0xe4, 0x0d, 0x91, 0xc5, 0x67, 0x5d, 0xcc, 0xc6, 0x0f, 0x17, 0x48, 0x66, 0x1d, 0xe3, 0xf0,
	0xcf, 0x04, 0xca, 0xb6, 0x1b, 0x5f, 0xc9, 0x1a, 0xe3, 0xbf, 0xd9, 0xe6, 0x9b, 0xa2, 0xfd, 0x78,
	0xee, 0x88, 0xa8, 0x34, 0x43, 0xd1, 0xac, 0xd8, 0xa7, 0xbe, 0x77, 0x2e, 0x3e, 0x56, 0xf8, 0xc7,
	0x94, 0xa1, 0xff, 0xa1, 0x41, 0x2b, 0x3f, 0x3c, 0xf0, 0x3c, 0xcd, 0xde, 0xb4, 0x4b, 0x73, 0x9b,
	0x9c, 0xb9, 0xef, 0x2d, 0x3b, 0xf7, 0xee, 0x03, 0xa4, 0x87, 0x19, 0x9b, 0x57, 0x07, 0x27, 0x6c,
	0x62, 0x1d, 0x8e, 0x8e, 0x9f, 0xe1, 0xfc, 0xea, 0x42, 0x53, 0x8e, 0xa5, 0x27, 0xa3, 0xa7, 0x83,
	0xe1, 0xb3, 0x8e, 0x76, 0xef, 0x0e, 0xd4, 0x33, 0xab, 0x95, 0x34, 0xa1, 0x36, 0x1c, 0x4c, 0x26,
	0x83, 0xe3, 0x5d, 0x63, 0x80, 0x0a, 0x55, 0x28, 0xef, 0x8f, 0x0e, 0x71, 0xd4, 0xed, 0xbc, 0x29,
	0xc3, 0xda, 0x63, 0xe1, 0x0f, 0xf6, 0x47, 0x23, 0x7b, 0x24, 0x90, 0x5b, 0xe9, 0x3e, 0x5d, 0xbc,
	0x1d, 0xfa, 0x2d, 0xf5, 0x55, 0xfc, 0xeb, 0xb8, 0x46, 0xbe, 0x82, 0x7a, 0xe6, 0xc0, 0x26, 0x05,
	0x81, 0x7e, 0xba, 0x40, 0x8a, 0x67, 0x38, 0xea, 0x3e, 0x82, 0x46, 0xf6, 0xd4, 0x58, 0x50, 0xee,
	0xe7, 0x94, 0x73, 0x17, 0x09, 0x6a, 0x0f, 0xa0, 0xa6, 0x8e, 0x63, 0x92, 0xbe, 0x53, 0x3c, 0xde,
	0xfb, 0x9b, 0xcb, 0x3e, 0x09, 0x13, 0x07, 0x08, 0x58, 0x7a, 0x34, 0x92, 0xf4, 0xe8, 0x5c, 0xbc,
	0x9d, 0x33, 0x91, 0x14, 0xef, 0x4c, 0x8e, 0x02, 0xa4, 0xc7, 0x24, 0xe9, 0x67, 0x44, 0x0b, 0x17,
	0xe6, 0x12, 0x04, 0xd1, 0x89, 0xcc, 0x6d, 0x91, 0x71, 0x62, 0xf1, 0xa2, 0xca, 0x38, 0x51, 0x3c,
	0x47, 0xd0, 0xd0, 0x0e, 0x54, 0xf8, 0x2d, 0x41, 0xfe, 0xb7, 0xf4, 0xb6, 0x58, 0x7c, 0x7a, 0x4b,
	0x3b, 0x5d, 0xe5, 0xff, 0x27, 0xbf, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x78, 0xe1, 0x03,
	0x69, 0x0e, 0x00, 0x00,
}
