// Code generated by protoc-gen-go.
// source: protobuf/bgpmond.proto
// DO NOT EDIT!

/*
Package bgpmond is a generated protocol buffer package.

It is generated from these files:
	protobuf/bgpmond.proto

It has these top-level messages:
	Empty
	GoBGPLinkModule
	PrefixHijackModule
	ListModulesResult
	RunModuleConfig
	RunModuleResult
	StartModuleConfig
	StartModuleResult
	StopModuleConfig
	CassandraSession
	FileSession
	CloseSessionConfig
	ListSessionsResult
	OpenSessionConfig
	OpenSessionResult
	WriteConfig
	ASNumberLocation
	BGPUpdateMessage
	IPAddressLocation
	Location
	PrefixLocation
*/
package bgpmond

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

//
// Module Messages
type ModuleType int32

const (
	ModuleType_GOBGP_LINK    ModuleType = 0
	ModuleType_PREFIX_HIJACK ModuleType = 1
)

var ModuleType_name = map[int32]string{
	0: "GOBGP_LINK",
	1: "PREFIX_HIJACK",
}
var ModuleType_value = map[string]int32{
	"GOBGP_LINK":    0,
	"PREFIX_HIJACK": 1,
}

func (x ModuleType) String() string {
	return proto.EnumName(ModuleType_name, int32(x))
}
func (ModuleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

//
// Session Messages
type SessionType int32

const (
	SessionType_CASSANDRA SessionType = 0
	SessionType_FILE      SessionType = 1
)

var SessionType_name = map[int32]string{
	0: "CASSANDRA",
	1: "FILE",
}
var SessionType_value = map[string]int32{
	"CASSANDRA": 0,
	"FILE":      1,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}
func (SessionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type WriteConfig_Type int32

const (
	WriteConfig_AS_NUMBER_LOCATION  WriteConfig_Type = 0
	WriteConfig_BGP_UPDATE          WriteConfig_Type = 1
	WriteConfig_IP_ADDRESS_LOCATION WriteConfig_Type = 2
	WriteConfig_PREFIX_LOCATION     WriteConfig_Type = 3
)

var WriteConfig_Type_name = map[int32]string{
	0: "AS_NUMBER_LOCATION",
	1: "BGP_UPDATE",
	2: "IP_ADDRESS_LOCATION",
	3: "PREFIX_LOCATION",
}
var WriteConfig_Type_value = map[string]int32{
	"AS_NUMBER_LOCATION":  0,
	"BGP_UPDATE":          1,
	"IP_ADDRESS_LOCATION": 2,
	"PREFIX_LOCATION":     3,
}

func (x WriteConfig_Type) String() string {
	return proto.EnumName(WriteConfig_Type_name, int32(x))
}
func (WriteConfig_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GoBGPLinkModule struct {
	Address      string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	OutSessionId []string `protobuf:"bytes,2,rep,name=out_session_id" json:"out_session_id,omitempty"`
}

func (m *GoBGPLinkModule) Reset()                    { *m = GoBGPLinkModule{} }
func (m *GoBGPLinkModule) String() string            { return proto.CompactTextString(m) }
func (*GoBGPLinkModule) ProtoMessage()               {}
func (*GoBGPLinkModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PrefixHijackModule struct {
	Prefix          string   `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	AsNumber        []uint32 `protobuf:"varint,2,rep,name=as_number" json:"as_number,omitempty"`
	PeriodicSeconds int32    `protobuf:"varint,3,opt,name=periodic_seconds" json:"periodic_seconds,omitempty"`
	TimeoutSeconds  int32    `protobuf:"varint,4,opt,name=timeout_seconds" json:"timeout_seconds,omitempty"`
	InSessionId     []string `protobuf:"bytes,5,rep,name=in_session_id" json:"in_session_id,omitempty"`
}

func (m *PrefixHijackModule) Reset()                    { *m = PrefixHijackModule{} }
func (m *PrefixHijackModule) String() string            { return proto.CompactTextString(m) }
func (*PrefixHijackModule) ProtoMessage()               {}
func (*PrefixHijackModule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

//
// Module Command Messages
type ListModulesResult struct {
	ModuleId []string `protobuf:"bytes,1,rep,name=module_id" json:"module_id,omitempty"`
}

func (m *ListModulesResult) Reset()                    { *m = ListModulesResult{} }
func (m *ListModulesResult) String() string            { return proto.CompactTextString(m) }
func (*ListModulesResult) ProtoMessage()               {}
func (*ListModulesResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RunModuleConfig struct {
	Type               ModuleType          `protobuf:"varint,1,opt,name=type,enum=bgpmond.ModuleType" json:"type,omitempty"`
	PrefixHijackModule *PrefixHijackModule `protobuf:"bytes,2,opt,name=prefix_hijack_module" json:"prefix_hijack_module,omitempty"`
}

func (m *RunModuleConfig) Reset()                    { *m = RunModuleConfig{} }
func (m *RunModuleConfig) String() string            { return proto.CompactTextString(m) }
func (*RunModuleConfig) ProtoMessage()               {}
func (*RunModuleConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RunModuleConfig) GetPrefixHijackModule() *PrefixHijackModule {
	if m != nil {
		return m.PrefixHijackModule
	}
	return nil
}

type RunModuleResult struct {
	ModuleMessage string `protobuf:"bytes,3,opt,name=module_message" json:"module_message,omitempty"`
}

func (m *RunModuleResult) Reset()                    { *m = RunModuleResult{} }
func (m *RunModuleResult) String() string            { return proto.CompactTextString(m) }
func (*RunModuleResult) ProtoMessage()               {}
func (*RunModuleResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StartModuleConfig struct {
	Type               ModuleType          `protobuf:"varint,1,opt,name=type,enum=bgpmond.ModuleType" json:"type,omitempty"`
	ModuleId           string              `protobuf:"bytes,2,opt,name=module_id" json:"module_id,omitempty"`
	GobgpLinkModule    *GoBGPLinkModule    `protobuf:"bytes,3,opt,name=gobgp_link_module" json:"gobgp_link_module,omitempty"`
	PrefixHijackModule *PrefixHijackModule `protobuf:"bytes,4,opt,name=prefix_hijack_module" json:"prefix_hijack_module,omitempty"`
}

func (m *StartModuleConfig) Reset()                    { *m = StartModuleConfig{} }
func (m *StartModuleConfig) String() string            { return proto.CompactTextString(m) }
func (*StartModuleConfig) ProtoMessage()               {}
func (*StartModuleConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartModuleConfig) GetGobgpLinkModule() *GoBGPLinkModule {
	if m != nil {
		return m.GobgpLinkModule
	}
	return nil
}

func (m *StartModuleConfig) GetPrefixHijackModule() *PrefixHijackModule {
	if m != nil {
		return m.PrefixHijackModule
	}
	return nil
}

type StartModuleResult struct {
	ModuleId string `protobuf:"bytes,3,opt,name=module_id" json:"module_id,omitempty"`
}

func (m *StartModuleResult) Reset()                    { *m = StartModuleResult{} }
func (m *StartModuleResult) String() string            { return proto.CompactTextString(m) }
func (*StartModuleResult) ProtoMessage()               {}
func (*StartModuleResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StopModuleConfig struct {
	ModuleId string `protobuf:"bytes,1,opt,name=module_id" json:"module_id,omitempty"`
}

func (m *StopModuleConfig) Reset()                    { *m = StopModuleConfig{} }
func (m *StopModuleConfig) String() string            { return proto.CompactTextString(m) }
func (*StopModuleConfig) ProtoMessage()               {}
func (*StopModuleConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CassandraSession struct {
	Username string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Hosts    []string `protobuf:"bytes,3,rep,name=hosts" json:"hosts,omitempty"`
}

func (m *CassandraSession) Reset()                    { *m = CassandraSession{} }
func (m *CassandraSession) String() string            { return proto.CompactTextString(m) }
func (*CassandraSession) ProtoMessage()               {}
func (*CassandraSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type FileSession struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
}

func (m *FileSession) Reset()                    { *m = FileSession{} }
func (m *FileSession) String() string            { return proto.CompactTextString(m) }
func (*FileSession) ProtoMessage()               {}
func (*FileSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

//
// Session Command Messages
type CloseSessionConfig struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
}

func (m *CloseSessionConfig) Reset()                    { *m = CloseSessionConfig{} }
func (m *CloseSessionConfig) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionConfig) ProtoMessage()               {}
func (*CloseSessionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type ListSessionsResult struct {
	SessionId []string `protobuf:"bytes,1,rep,name=session_id" json:"session_id,omitempty"`
}

func (m *ListSessionsResult) Reset()                    { *m = ListSessionsResult{} }
func (m *ListSessionsResult) String() string            { return proto.CompactTextString(m) }
func (*ListSessionsResult) ProtoMessage()               {}
func (*ListSessionsResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type OpenSessionConfig struct {
	Type             SessionType       `protobuf:"varint,1,opt,name=type,enum=bgpmond.SessionType" json:"type,omitempty"`
	SessionId        string            `protobuf:"bytes,2,opt,name=session_id" json:"session_id,omitempty"`
	CassandraSession *CassandraSession `protobuf:"bytes,3,opt,name=cassandra_session" json:"cassandra_session,omitempty"`
	FileSession      *FileSession      `protobuf:"bytes,4,opt,name=file_session" json:"file_session,omitempty"`
}

func (m *OpenSessionConfig) Reset()                    { *m = OpenSessionConfig{} }
func (m *OpenSessionConfig) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionConfig) ProtoMessage()               {}
func (*OpenSessionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OpenSessionConfig) GetCassandraSession() *CassandraSession {
	if m != nil {
		return m.CassandraSession
	}
	return nil
}

func (m *OpenSessionConfig) GetFileSession() *FileSession {
	if m != nil {
		return m.FileSession
	}
	return nil
}

type OpenSessionResult struct {
	SessionId string `protobuf:"bytes,3,opt,name=session_id" json:"session_id,omitempty"`
}

func (m *OpenSessionResult) Reset()                    { *m = OpenSessionResult{} }
func (m *OpenSessionResult) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionResult) ProtoMessage()               {}
func (*OpenSessionResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

//
// Write Messages
type WriteConfig struct {
	Type              WriteConfig_Type   `protobuf:"varint,1,opt,name=type,enum=bgpmond.WriteConfig_Type" json:"type,omitempty"`
	AsNumberLocation  *ASNumberLocation  `protobuf:"bytes,2,opt,name=as_number_location" json:"as_number_location,omitempty"`
	BgpUpdateMessage  *BGPUpdateMessage  `protobuf:"bytes,3,opt,name=bgp_update_message" json:"bgp_update_message,omitempty"`
	IpAddressLocation *IPAddressLocation `protobuf:"bytes,4,opt,name=ip_address_location" json:"ip_address_location,omitempty"`
	PrefixLocation    *PrefixLocation    `protobuf:"bytes,5,opt,name=prefix_location" json:"prefix_location,omitempty"`
}

func (m *WriteConfig) Reset()                    { *m = WriteConfig{} }
func (m *WriteConfig) String() string            { return proto.CompactTextString(m) }
func (*WriteConfig) ProtoMessage()               {}
func (*WriteConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *WriteConfig) GetAsNumberLocation() *ASNumberLocation {
	if m != nil {
		return m.AsNumberLocation
	}
	return nil
}

func (m *WriteConfig) GetBgpUpdateMessage() *BGPUpdateMessage {
	if m != nil {
		return m.BgpUpdateMessage
	}
	return nil
}

func (m *WriteConfig) GetIpAddressLocation() *IPAddressLocation {
	if m != nil {
		return m.IpAddressLocation
	}
	return nil
}

func (m *WriteConfig) GetPrefixLocation() *PrefixLocation {
	if m != nil {
		return m.PrefixLocation
	}
	return nil
}

type ASNumberLocation struct {
	ASNumber    uint32    `protobuf:"varint,1,opt,name=ASNumber" json:"ASNumber,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
}

func (m *ASNumberLocation) Reset()                    { *m = ASNumberLocation{} }
func (m *ASNumberLocation) String() string            { return proto.CompactTextString(m) }
func (*ASNumberLocation) ProtoMessage()               {}
func (*ASNumberLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ASNumberLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type BGPUpdateMessage struct {
}

func (m *BGPUpdateMessage) Reset()                    { *m = BGPUpdateMessage{} }
func (m *BGPUpdateMessage) String() string            { return proto.CompactTextString(m) }
func (*BGPUpdateMessage) ProtoMessage()               {}
func (*BGPUpdateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type IPAddressLocation struct {
	IpAddress   string    `protobuf:"bytes,1,opt,name=ip_address" json:"ip_address,omitempty"`
	MeasureDate string    `protobuf:"bytes,2,opt,name=measure_date" json:"measure_date,omitempty"`
	Location    *Location `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
}

func (m *IPAddressLocation) Reset()                    { *m = IPAddressLocation{} }
func (m *IPAddressLocation) String() string            { return proto.CompactTextString(m) }
func (*IPAddressLocation) ProtoMessage()               {}
func (*IPAddressLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *IPAddressLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	CountryCode string  `protobuf:"bytes,1,opt,name=country_code" json:"country_code,omitempty"`
	StateCode   string  `protobuf:"bytes,2,opt,name=state_code" json:"state_code,omitempty"`
	City        string  `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	Latitude    float64 `protobuf:"fixed64,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,5,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type PrefixLocation struct {
	PrefixIpAddress string    `protobuf:"bytes,1,opt,name=prefix_ip_address" json:"prefix_ip_address,omitempty"`
	PrefixMask      uint32    `protobuf:"varint,2,opt,name=prefix_mask" json:"prefix_mask,omitempty"`
	MeasureDate     string    `protobuf:"bytes,3,opt,name=measure_date" json:"measure_date,omitempty"`
	Location        *Location `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
}

func (m *PrefixLocation) Reset()                    { *m = PrefixLocation{} }
func (m *PrefixLocation) String() string            { return proto.CompactTextString(m) }
func (*PrefixLocation) ProtoMessage()               {}
func (*PrefixLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PrefixLocation) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "bgpmond.Empty")
	proto.RegisterType((*GoBGPLinkModule)(nil), "bgpmond.GoBGPLinkModule")
	proto.RegisterType((*PrefixHijackModule)(nil), "bgpmond.PrefixHijackModule")
	proto.RegisterType((*ListModulesResult)(nil), "bgpmond.ListModulesResult")
	proto.RegisterType((*RunModuleConfig)(nil), "bgpmond.RunModuleConfig")
	proto.RegisterType((*RunModuleResult)(nil), "bgpmond.RunModuleResult")
	proto.RegisterType((*StartModuleConfig)(nil), "bgpmond.StartModuleConfig")
	proto.RegisterType((*StartModuleResult)(nil), "bgpmond.StartModuleResult")
	proto.RegisterType((*StopModuleConfig)(nil), "bgpmond.StopModuleConfig")
	proto.RegisterType((*CassandraSession)(nil), "bgpmond.CassandraSession")
	proto.RegisterType((*FileSession)(nil), "bgpmond.FileSession")
	proto.RegisterType((*CloseSessionConfig)(nil), "bgpmond.CloseSessionConfig")
	proto.RegisterType((*ListSessionsResult)(nil), "bgpmond.ListSessionsResult")
	proto.RegisterType((*OpenSessionConfig)(nil), "bgpmond.OpenSessionConfig")
	proto.RegisterType((*OpenSessionResult)(nil), "bgpmond.OpenSessionResult")
	proto.RegisterType((*WriteConfig)(nil), "bgpmond.WriteConfig")
	proto.RegisterType((*ASNumberLocation)(nil), "bgpmond.ASNumberLocation")
	proto.RegisterType((*BGPUpdateMessage)(nil), "bgpmond.BGPUpdateMessage")
	proto.RegisterType((*IPAddressLocation)(nil), "bgpmond.IPAddressLocation")
	proto.RegisterType((*Location)(nil), "bgpmond.Location")
	proto.RegisterType((*PrefixLocation)(nil), "bgpmond.PrefixLocation")
	proto.RegisterEnum("bgpmond.ModuleType", ModuleType_name, ModuleType_value)
	proto.RegisterEnum("bgpmond.SessionType", SessionType_name, SessionType_value)
	proto.RegisterEnum("bgpmond.WriteConfig_Type", WriteConfig_Type_name, WriteConfig_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Bgpmond service

type BgpmondClient interface {
	CloseSession(ctx context.Context, in *CloseSessionConfig, opts ...grpc.CallOption) (*Empty, error)
	ListModules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListModulesResult, error)
	ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsResult, error)
	RunModule(ctx context.Context, in *RunModuleConfig, opts ...grpc.CallOption) (*RunModuleResult, error)
	StartModule(ctx context.Context, in *StartModuleConfig, opts ...grpc.CallOption) (*StartModuleResult, error)
	StopModule(ctx context.Context, in *StopModuleConfig, opts ...grpc.CallOption) (*Empty, error)
	OpenSession(ctx context.Context, in *OpenSessionConfig, opts ...grpc.CallOption) (*OpenSessionResult, error)
}

type bgpmondClient struct {
	cc *grpc.ClientConn
}

func NewBgpmondClient(cc *grpc.ClientConn) BgpmondClient {
	return &bgpmondClient{cc}
}

func (c *bgpmondClient) CloseSession(ctx context.Context, in *CloseSessionConfig, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/CloseSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) ListModules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListModulesResult, error) {
	out := new(ListModulesResult)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/ListModules", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsResult, error) {
	out := new(ListSessionsResult)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/ListSessions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) RunModule(ctx context.Context, in *RunModuleConfig, opts ...grpc.CallOption) (*RunModuleResult, error) {
	out := new(RunModuleResult)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/RunModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) StartModule(ctx context.Context, in *StartModuleConfig, opts ...grpc.CallOption) (*StartModuleResult, error) {
	out := new(StartModuleResult)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/StartModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) StopModule(ctx context.Context, in *StopModuleConfig, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/StopModule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpmondClient) OpenSession(ctx context.Context, in *OpenSessionConfig, opts ...grpc.CallOption) (*OpenSessionResult, error) {
	out := new(OpenSessionResult)
	err := grpc.Invoke(ctx, "/bgpmond.Bgpmond/OpenSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bgpmond service

type BgpmondServer interface {
	CloseSession(context.Context, *CloseSessionConfig) (*Empty, error)
	ListModules(context.Context, *Empty) (*ListModulesResult, error)
	ListSessions(context.Context, *Empty) (*ListSessionsResult, error)
	RunModule(context.Context, *RunModuleConfig) (*RunModuleResult, error)
	StartModule(context.Context, *StartModuleConfig) (*StartModuleResult, error)
	StopModule(context.Context, *StopModuleConfig) (*Empty, error)
	OpenSession(context.Context, *OpenSessionConfig) (*OpenSessionResult, error)
}

func RegisterBgpmondServer(s *grpc.Server, srv BgpmondServer) {
	s.RegisterService(&_Bgpmond_serviceDesc, srv)
}

func _Bgpmond_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CloseSessionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).CloseSession(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bgpmond_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).ListModules(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bgpmond_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).ListSessions(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bgpmond_RunModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RunModuleConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).RunModule(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bgpmond_StartModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StartModuleConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).StartModule(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bgpmond_StopModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StopModuleConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).StopModule(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bgpmond_OpenSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(OpenSessionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BgpmondServer).OpenSession(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Bgpmond_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bgpmond.Bgpmond",
	HandlerType: (*BgpmondServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseSession",
			Handler:    _Bgpmond_CloseSession_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _Bgpmond_ListModules_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Bgpmond_ListSessions_Handler,
		},
		{
			MethodName: "RunModule",
			Handler:    _Bgpmond_RunModule_Handler,
		},
		{
			MethodName: "StartModule",
			Handler:    _Bgpmond_StartModule_Handler,
		},
		{
			MethodName: "StopModule",
			Handler:    _Bgpmond_StopModule_Handler,
		},
		{
			MethodName: "OpenSession",
			Handler:    _Bgpmond_OpenSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 1156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xe3, 0x54,
	0x14, 0x1e, 0x37, 0xc9, 0x34, 0x39, 0x6e, 0x12, 0xe7, 0xb6, 0x9a, 0xe9, 0xa4, 0x20, 0x06, 0x8b,
	0x9f, 0x4e, 0x25, 0xda, 0x51, 0x67, 0x01, 0x08, 0x21, 0xe1, 0x26, 0x6d, 0x27, 0x33, 0x69, 0x1b,
	0xec, 0x56, 0xb0, 0x40, 0x32, 0x6e, 0xec, 0x76, 0xcc, 0x24, 0xb6, 0xe5, 0x1f, 0x41, 0x77, 0x2c,
	0xd8, 0xf0, 0x0a, 0xbc, 0x04, 0x7b, 0x76, 0xbc, 0x03, 0x5b, 0x5e, 0x81, 0x67, 0xe0, 0xfe, 0xfb,
	0x2f, 0x80, 0x34, 0x12, 0x3b, 0x9f, 0xef, 0x9e, 0x73, 0x7c, 0xce, 0x77, 0xbf, 0x73, 0xef, 0x85,
	0x07, 0x51, 0x1c, 0xa6, 0xe1, 0x75, 0x76, 0x73, 0x70, 0x7d, 0x1b, 0x2d, 0xc3, 0xc0, 0xdd, 0xa7,
	0x00, 0x5a, 0xe7, 0xa6, 0xbe, 0x0e, 0xad, 0xe3, 0x65, 0x94, 0xde, 0xe9, 0x5f, 0x42, 0xff, 0x34,
	0x3c, 0x3a, 0x9d, 0x4d, 0xfd, 0xe0, 0xf5, 0x59, 0xe8, 0x66, 0x0b, 0x0f, 0x6d, 0xc3, 0xba, 0xe3,
	0xba, 0xb1, 0x97, 0x24, 0xdb, 0xca, 0x63, 0x65, 0xb7, 0x63, 0x0a, 0x13, 0xbd, 0x07, 0xbd, 0x30,
	0x4b, 0xed, 0x04, 0x7f, 0xfb, 0x61, 0x60, 0xfb, 0xee, 0xf6, 0xda, 0xe3, 0x06, 0x76, 0xd8, 0xc0,
	0xa8, 0xc5, 0xc0, 0x89, 0xab, 0xff, 0xae, 0x00, 0x9a, 0xc5, 0xde, 0x8d, 0xff, 0xc3, 0x73, 0xff,
	0x3b, 0x67, 0x2e, 0xd2, 0x3e, 0x80, 0xfb, 0x11, 0x45, 0x79, 0x56, 0x6e, 0xa1, 0x1d, 0xe8, 0x38,
	0x89, 0x1d, 0x64, 0xcb, 0x6b, 0x2f, 0xa6, 0xf9, 0xba, 0x66, 0xdb, 0x49, 0xce, 0xa9, 0x8d, 0x9e,
	0x80, 0x16, 0x79, 0xb1, 0x1f, 0xba, 0xfe, 0x1c, 0xff, 0x76, 0x8e, 0x4b, 0x4f, 0xb6, 0x1b, 0x38,
	0xbc, 0x65, 0xf6, 0x05, 0x6e, 0x31, 0x18, 0x7d, 0x08, 0xfd, 0xd4, 0x5f, 0x7a, 0xac, 0x40, 0xe6,
	0xd9, 0xa4, 0x9e, 0x3d, 0x0e, 0x0b, 0x47, 0x1d, 0xba, 0x7e, 0x50, 0x6c, 0xa2, 0x45, 0x9b, 0x50,
	0xfd, 0x20, 0xef, 0xe1, 0x29, 0x0c, 0xa6, 0x7e, 0x92, 0xb2, 0xd2, 0x13, 0xd3, 0x4b, 0xb2, 0x45,
	0x4a, 0x2a, 0x5d, 0x52, 0x80, 0x04, 0x29, 0x34, 0xa8, 0xcd, 0x00, 0x1c, 0xf1, 0xb3, 0x02, 0x7d,
	0x33, 0x0b, 0x58, 0xc4, 0x28, 0x0c, 0x6e, 0xfc, 0x5b, 0x5c, 0x52, 0x33, 0xbd, 0x8b, 0x3c, 0xda,
	0x70, 0xef, 0x70, 0x73, 0x5f, 0x6c, 0x06, 0x73, 0xba, 0xc4, 0x4b, 0x26, 0x75, 0x40, 0x67, 0xb0,
	0xc5, 0xd8, 0xb0, 0x5f, 0x51, 0xca, 0x6c, 0x96, 0x16, 0xd3, 0xa1, 0xec, 0xaa, 0x87, 0x3b, 0x32,
	0xb0, 0x4e, 0xab, 0x89, 0xa2, 0x1a, 0xa6, 0x7f, 0x52, 0x28, 0x85, 0xd7, 0xfe, 0x3e, 0xf4, 0x78,
	0xed, 0x4b, 0xdc, 0xa4, 0x73, 0xeb, 0x51, 0x1a, 0x3b, 0x66, 0x97, 0xa1, 0x67, 0x0c, 0xd4, 0xff,
	0x52, 0x60, 0x60, 0xa5, 0x4e, 0x9c, 0xbe, 0x59, 0x1f, 0x25, 0x86, 0xd6, 0xe8, 0x0f, 0x24, 0x43,
	0x68, 0x0c, 0x83, 0xdb, 0x10, 0x87, 0xda, 0x0b, 0xac, 0x35, 0xd1, 0x61, 0x83, 0x76, 0xb8, 0x2d,
	0x53, 0x56, 0xc4, 0x68, 0xf6, 0x69, 0x48, 0x41, 0x9d, 0xff, 0x44, 0x55, 0xf3, 0xcd, 0xa8, 0x7a,
	0x5a, 0xea, 0x77, 0xd5, 0x46, 0x37, 0xca, 0x6d, 0xe8, 0x07, 0xa0, 0x59, 0x69, 0x18, 0x95, 0x08,
	0xaa, 0x28, 0xa3, 0x1c, 0xf0, 0x2d, 0x68, 0x23, 0x07, 0xd3, 0x1b, 0xb8, 0xb1, 0xc3, 0x15, 0x86,
	0x86, 0xd0, 0xce, 0x12, 0x2f, 0x0e, 0x9c, 0xa5, 0x27, 0xfc, 0x85, 0x4d, 0xd6, 0x22, 0xec, 0xff,
	0x7d, 0x18, 0x4b, 0x0e, 0x85, 0x8d, 0xb6, 0xa0, 0xf5, 0x2a, 0x4c, 0x52, 0x32, 0x04, 0x44, 0x7e,
	0xcc, 0xd0, 0x9f, 0x80, 0x7a, 0xe2, 0x2f, 0xbc, 0x42, 0xf2, 0x1b, 0x6c, 0x16, 0x93, 0x0b, 0x5b,
	0x7f, 0x06, 0x68, 0xb4, 0x08, 0x13, 0xe1, 0xcb, 0xeb, 0x7f, 0x1b, 0xa0, 0x30, 0x0f, 0x2c, 0xa6,
	0x93, 0xc8, 0x69, 0xc0, 0x41, 0x64, 0x1a, 0x78, 0x8c, 0x18, 0x87, 0x6a, 0x50, 0xa3, 0x1c, 0xf4,
	0x27, 0x96, 0xd2, 0x45, 0xe4, 0x05, 0xe5, 0x3f, 0xed, 0x96, 0xa4, 0xb4, 0x25, 0xb7, 0x8b, 0x7b,
	0x15, 0xb4, 0x54, 0x4e, 0xbf, 0x56, 0xa9, 0x09, 0x9d, 0xc0, 0x60, 0x2e, 0x58, 0x15, 0xc3, 0xcc,
	0xd5, 0xf4, 0x48, 0x66, 0xad, 0xf2, 0x6e, 0x6a, 0xf3, 0xea, 0x4e, 0x7c, 0x0c, 0x1b, 0x84, 0x1c,
	0x99, 0x82, 0xe9, 0x28, 0x2f, 0xac, 0x40, 0xac, 0xa9, 0xde, 0xe4, 0x86, 0x7e, 0x58, 0x6a, 0x6f,
	0x25, 0x27, 0x8d, 0x2a, 0x91, 0xbf, 0x35, 0x40, 0xfd, 0x2a, 0xf6, 0x53, 0xa1, 0x9b, 0x8f, 0x4a,
	0x6c, 0xe4, 0x75, 0x17, 0x7c, 0xf6, 0x0b, 0x94, 0x9c, 0x02, 0x92, 0x47, 0xa5, 0xbd, 0x08, 0xe7,
	0x4e, 0x4a, 0x2a, 0x5e, 0xab, 0x34, 0x6d, 0x58, 0xec, 0xf0, 0x9c, 0x72, 0x07, 0x53, 0x13, 0xc7,
	0xa9, 0x40, 0x48, 0x22, 0x32, 0x88, 0x59, 0xe4, 0x3a, 0x69, 0xf9, 0x44, 0x28, 0x26, 0xc2, 0x93,
	0x78, 0x45, 0x3d, 0xf8, 0xe9, 0x60, 0x6a, 0x78, 0xa5, 0x84, 0xa0, 0x17, 0xb0, 0xe9, 0x47, 0x36,
	0xbf, 0x1f, 0xf2, 0x92, 0x18, 0x89, 0x43, 0x99, 0x69, 0x32, 0x33, 0x98, 0x8b, 0xac, 0x69, 0xe0,
	0x47, 0x15, 0x08, 0x7d, 0x01, 0x7d, 0x3e, 0xd9, 0x32, 0x4f, 0x8b, 0xe6, 0x79, 0x58, 0x19, 0x6a,
	0x99, 0xa4, 0x17, 0x95, 0x6c, 0xfd, 0x1b, 0x68, 0x12, 0xb6, 0xf0, 0x55, 0x83, 0x0c, 0xcb, 0x3e,
	0xbf, 0x3a, 0x3b, 0x3a, 0x36, 0xed, 0xe9, 0xc5, 0xc8, 0xb8, 0x9c, 0x5c, 0x9c, 0x6b, 0xf7, 0x50,
	0x0f, 0x00, 0xf7, 0x64, 0x5f, 0xcd, 0xc6, 0xc6, 0xe5, 0xb1, 0xa6, 0xa0, 0x87, 0xb0, 0x39, 0x99,
	0xd9, 0xc6, 0x78, 0x6c, 0x1e, 0x5b, 0x56, 0xee, 0xb8, 0x86, 0x36, 0xa1, 0x3f, 0x33, 0x8f, 0x4f,
	0x26, 0x5f, 0xe7, 0x60, 0x43, 0xff, 0x51, 0x01, 0xad, 0xca, 0x2d, 0x99, 0x35, 0x81, 0xd1, 0x5d,
	0x24, 0x97, 0x17, 0xb7, 0xd1, 0xbb, 0xb0, 0xb1, 0xf4, 0x9c, 0x24, 0x8b, 0x3d, 0x9b, 0x70, 0xc6,
	0x35, 0xac, 0x72, 0x6c, 0x8c, 0x21, 0x2c, 0x80, 0xb6, 0x6c, 0x96, 0xd1, 0x3f, 0x90, 0xcd, 0xca,
	0x36, 0xa5, 0x8b, 0x8e, 0x40, 0xab, 0x6e, 0x8a, 0xfe, 0x13, 0x9e, 0xb3, 0x1a, 0xbf, 0x44, 0x88,
	0xf9, 0xc6, 0x88, 0x89, 0x96, 0x9c, 0xff, 0x0f, 0xa5, 0xfd, 0xa2, 0x40, 0x5b, 0xfe, 0x1d, 0xa7,
	0x9f, 0x87, 0x59, 0x90, 0xc6, 0x77, 0xf6, 0x3c, 0x74, 0xc5, 0x29, 0xa4, 0x72, 0x6c, 0x84, 0x21,
	0x3a, 0x29, 0x29, 0x51, 0x1f, 0x75, 0x10, 0xe3, 0x4d, 0x10, 0xba, 0x8c, 0xa0, 0x39, 0xf7, 0xd3,
	0x3b, 0x3e, 0x42, 0xf4, 0x9b, 0x70, 0xbd, 0xc0, 0xf9, 0xd3, 0xcc, 0x65, 0xc7, 0xbd, 0x62, 0x4a,
	0x1b, 0xbd, 0x05, 0x9d, 0x45, 0x18, 0xdc, 0xb2, 0xc5, 0x16, 0x5d, 0xcc, 0x01, 0xfd, 0x57, 0x05,
	0x7a, 0x65, 0xed, 0xa0, 0x3d, 0x18, 0x70, 0xb5, 0xd5, 0x78, 0xe2, 0x32, 0x9c, 0x48, 0xb6, 0xde,
	0x01, 0x95, 0xfb, 0x2e, 0x9d, 0xe4, 0x35, 0x2d, 0xb6, 0x6b, 0x02, 0x83, 0xce, 0x30, 0x52, 0xa3,
	0xb3, 0xf1, 0xef, 0x74, 0x36, 0xff, 0x93, 0xce, 0xbd, 0x03, 0x80, 0xfc, 0x76, 0x25, 0xc2, 0x3d,
	0xbd, 0x20, 0xd2, 0x9d, 0x4e, 0xce, 0x5f, 0x62, 0x21, 0x0f, 0xa0, 0xcb, 0xf5, 0xf9, 0x7c, 0xf2,
	0xc2, 0x18, 0xbd, 0xd4, 0x94, 0xbd, 0x0f, 0x40, 0x2d, 0x9c, 0xa1, 0xa8, 0x0b, 0x9d, 0x91, 0x61,
	0x59, 0xc6, 0xf9, 0xd8, 0x34, 0x70, 0x40, 0x1b, 0x9a, 0x27, 0x93, 0x29, 0xd6, 0xfc, 0xe1, 0x1f,
	0x0d, 0x58, 0x3f, 0x62, 0xff, 0x45, 0x9f, 0xc3, 0x46, 0xf1, 0x32, 0x40, 0xf9, 0xed, 0x59, 0xbf,
	0x23, 0x86, 0x3d, 0xb9, 0xc8, 0x5e, 0x8e, 0xf7, 0xd0, 0x67, 0xa0, 0x16, 0x1e, 0x49, 0xa8, 0xe2,
	0x30, 0xcc, 0xc7, 0xbf, 0xf6, 0x94, 0xc2, 0xc1, 0xf8, 0xdf, 0xc5, 0x3b, 0xa5, 0x16, 0xbd, 0x53,
	0x8a, 0x2e, 0x5f, 0x3d, 0x38, 0xdc, 0x80, 0x8e, 0x7c, 0xe2, 0xa0, 0xfc, 0xf9, 0x50, 0x79, 0x81,
	0x0d, 0x57, 0xac, 0xc8, 0x14, 0xa7, 0x98, 0xb1, 0xfc, 0xea, 0x47, 0x79, 0xb9, 0xb5, 0x07, 0xd0,
	0x70, 0xe5, 0x9a, 0x4c, 0xf4, 0x29, 0x40, 0xfe, 0x22, 0x40, 0x8f, 0x0a, 0xbe, 0xe5, 0x67, 0xc2,
	0x0a, 0x0a, 0x71, 0x0d, 0x85, 0x4b, 0xa4, 0x50, 0x43, 0xed, 0xe6, 0x1c, 0xae, 0x5c, 0x13, 0x35,
	0x5c, 0xdf, 0xa7, 0x0f, 0xfc, 0x67, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x03, 0xc6, 0xff, 0x39,
	0xfa, 0x0b, 0x00, 0x00,
}
